"""Typed in-process view of the finance ontology.

Loaders + generator live here (not in compile.py) so importing them via
`src.ontology` doesn't collide with running `python -m src.ontology.compile`.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

_DEFAULT_YAML = Path(__file__).resolve().parents[2] / "data" / "ontology" / "finance.yaml"


# --------------------------------------------------------------------------
# Typed view
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class Property:
    name: str
    type: str
    identifier: bool = False
    index: bool = False
    pii: bool = False
    default: Any = None
    vector: dict | None = None  # { dim, similarity }


@dataclass(frozen=True)
class Entity:
    name: str
    description: str
    properties: tuple[Property, ...]

    @property
    def identifier(self) -> Property | None:
        for p in self.properties:
            if p.identifier:
                return p
        return None


@dataclass(frozen=True)
class Relationship:
    type: str
    source: str
    target: str
    cardinality: str
    description: str = ""


@dataclass(frozen=True)
class Ontology:
    version: int
    namespace: str
    entities: tuple[Entity, ...]
    relationships: tuple[Relationship, ...]

    def entity(self, name: str) -> Entity | None:
        for e in self.entities:
            if e.name == name:
                return e
        return None

    def pii_properties(self) -> dict[str, tuple[str, ...]]:
        """{label: (prop_name, …)} of every property flagged pii: true.

        The PII filter that runs on raw statement text doesn't need this —
        it works pre-ingest. This is for any downstream surface that
        returns graph nodes to a user / LLM and needs to know which
        properties to redact.
        """
        return {
            e.name: tuple(p.name for p in e.properties if p.pii)
            for e in self.entities
            if any(p.pii for p in e.properties)
        }


# --------------------------------------------------------------------------
# Loader
# --------------------------------------------------------------------------

def load_ontology(path: Path | str = _DEFAULT_YAML) -> Ontology:
    raw = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    entities = tuple(
        Entity(
            name=name,
            description=str(spec.get("description", "")).strip(),
            properties=tuple(_parse_property(p) for p in spec.get("properties", [])),
        )
        for name, spec in (raw.get("entities") or {}).items()
    )
    rels = tuple(
        Relationship(
            type=r["type"],
            source=r["from"],
            target=r["to"],
            cardinality=str(r.get("cardinality", "many_to_one")),
            description=str(r.get("description", "")).strip(),
        )
        for r in (raw.get("relationships") or [])
    )
    return Ontology(
        version=int(raw.get("version", 1)),
        namespace=str(raw.get("namespace", "finance")),
        entities=entities,
        relationships=rels,
    )


def _parse_property(spec: dict) -> Property:
    vector = spec.get("vector")
    return Property(
        name=str(spec["name"]),
        type=str(spec.get("type", "string")),
        identifier=bool(spec.get("identifier", False)),
        index=bool(spec.get("index", False)),
        pii=bool(spec.get("pii", False)),
        default=spec.get("default"),
        vector=vector if isinstance(vector, dict) else None,
    )


# --------------------------------------------------------------------------
# Cypher generator
# --------------------------------------------------------------------------

_HEADER = """// Neo4j schema for the finance context graph.
//
// AUTOGENERATED from data/ontology/finance.yaml.
// Do not hand-edit — run `python -m src.ontology.compile --write`.
//
// Apply with: cypher-shell -u neo4j -p ... < src/ontology/schema.cypher
"""


def to_cypher(ontology: Ontology) -> str:
    out: list[str] = [_HEADER.strip(), ""]
    out.append("// Uniqueness constraints (also create indexes implicitly):")
    for entity in ontology.entities:
        ident = entity.identifier
        if not ident:
            continue
        cname = _constraint_name(entity.name, ident.name)
        var = _short_var(entity.name)
        out.append(
            f"CREATE CONSTRAINT {cname} IF NOT EXISTS "
            f"FOR ({var}:{entity.name}) REQUIRE {var}.{ident.name} IS UNIQUE;"
        )

    out += ["", "// Hot-path indexes:"]
    for entity in ontology.entities:
        for prop in entity.properties:
            if prop.identifier or not prop.index:
                continue
            iname = _index_name(entity.name, prop.name)
            var = _short_var(entity.name)
            out.append(
                f"CREATE INDEX {iname} IF NOT EXISTS "
                f"FOR ({var}:{entity.name}) ON ({var}.{prop.name});"
            )

    vector_blocks: list[str] = []
    for entity in ontology.entities:
        for prop in entity.properties:
            if not prop.vector:
                continue
            iname = _index_name(entity.name, prop.name) + "_vec"
            var = _short_var(entity.name)
            dim = int(prop.vector.get("dim", 1536))
            sim = str(prop.vector.get("similarity", "cosine"))
            vector_blocks.append(
                f"CREATE VECTOR INDEX {iname} IF NOT EXISTS\n"
                f"  FOR ({var}:{entity.name}) ON ({var}.{prop.name})\n"
                f"  OPTIONS {{ indexConfig: {{ `vector.dimensions`: {dim}, "
                f"`vector.similarity_function`: '{sim}' }} }};"
            )
    if vector_blocks:
        out += ["", "// Vector indexes:"]
        out += vector_blocks

    return "\n".join(out) + "\n"


def _short_var(label: str) -> str:
    table = {
        "Person": "p", "Account": "a", "Statement": "s", "Transaction": "t",
        "Merchant": "m", "Category": "c", "Month": "mo", "Day": "d",
        "Location": "l", "DescriptionTemplate": "dt", "Alert": "al",
    }
    if label in table:
        return table[label]
    return label[:1].lower() or "n"


def _constraint_name(label: str, prop: str) -> str:
    return f"{_snake(label)}_{_snake(prop)}"


def _index_name(label: str, prop: str) -> str:
    return f"{_snake(label)}_{_snake(prop)}"


def _snake(name: str) -> str:
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()
